### PR TITLE
Fixed example. 

### PR DESCRIPTION
**Pull request by mitnuh**
Would be more confident if I could test it with a better camera... The example takes pictures, downloads them and displays all the config ok. 

Gphoto2 can only change a few basic settings on my camera so I could only test the stuff under the Camera Setting submenu.

Made a screenshot so you can let me know if anything looks wrong :)

screenshot

### CODE REVIEW

**Comment by mitnuh** [comment]
Not merging yet because it looks like I messed up the travis build again...

**Comment by lwille** [comment]
I don't really see how your changes could break the CI, it just seems like `libgphoto-2-6-dev` can't be found any more :thinking:

**Comment by mitnuh** [comment]
Ah ok, I assumed worse, iirc the version from main gphoto ppa has a different api and I couldn't find a replacement ppa. Which is why I'm currently reading "how to upload a package to PPA".

**Comment by Sija** [comment]
@mitnuh Weird, [mine](https://github.com/Sija/gphoto2.cr/blob/213eb9acf6da04e7e305b002a17de7671ab18c2f/.travis.yml) still works...

**Comment by mitnuh** [comment]
Ohh thank you, that helped. I'm new and clueless with travis and didn't realise there was a distro choice.

**Pull request merged**
