### PR TITLE
v0.2

### LINKED ISSUE #67: Porting to NAN
The module needs porting to NAN in order to assure compability with previous and future versions of Node and V8.

Development is done in [feature/nan](https://github.com/lwille/node-gphoto2/tree/feature/nan).

related issues: #65

Tasks so far:
- [X] Replace bindings with NAN macros
- [x] Reimplement camera settings (were removed through removal of cvv8)
- [ ] Refactor async functions to use NanAsyncWorker
- [ ] Use injected (bunyan?) logger instead of logCallback

### PR DESCRIPTION
**Pull request by Sija**
It's a PR tracking new release, refactored with [nodejs/nan](https://github.com/nodejs/nan) which makes it compatible with newer node.js versions.

Supplements #92.
Closes #67.

Thanks to @mitnuh for making it happen!

### CODE REVIEW

**Comment by Sija** [comment]
@lwille There's still a task left undone:

>- [ ] Refactor async functions to use NanAsyncWorker

Are you OK with merging this PR without it?

**Comment by lwille** [comment]
Sure thing, if I remember correctly it’s not necessarily required and can
be implemented in the next minor.

-- 
Leonhardt Wille

**Comment by Sija** [comment]
So it seems we're ready to 🎲 :)

**Comment by lwille** [comment]
I added NPM credentials to the .travis-ci.yml so we can have automated releases.

please merge and push a `0.2.0` tag on `master`

**Pull request merged**
